//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuleBotClassLibrary.RessourceManager {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class botResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal botResource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModuleBotClassLibrary.RessourceManager.botResource", typeof(botResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à add role to  user.
        /// </summary>
        internal static string addroleCommand {
            get {
                return ResourceManager.GetString("addroleCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à add song to queue.
        /// </summary>
        internal static string addSongAudioCommand {
            get {
                return ResourceManager.GetString("addSongAudioCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ban user using discord member .
        /// </summary>
        internal static string banCommand {
            get {
                return ResourceManager.GetString("banCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à change Bot Status.
        /// </summary>
        internal static string botStatusCommand {
            get {
                return ResourceManager.GetString("botStatusCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à add black &amp; white effect.
        /// </summary>
        internal static string bwCommand {
            get {
                return ResourceManager.GetString("bwCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à check rappel.
        /// </summary>
        internal static string checkRappelCmd {
            get {
                return ResourceManager.GetString("checkRappelCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check a ticket.
        /// </summary>
        internal static string checkTicketCommand {
            get {
                return ResourceManager.GetString("checkTicketCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à clear all messages in channel.
        /// </summary>
        internal static string cleanallCommand {
            get {
                return ResourceManager.GetString("cleanallCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à clear queue.
        /// </summary>
        internal static string clearAudioCommand {
            get {
                return ResourceManager.GetString("clearAudioCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à clear x message in channel.
        /// </summary>
        internal static string clearCommand {
            get {
                return ResourceManager.GetString("clearCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à clear image directory server.
        /// </summary>
        internal static string clearDirCommand {
            get {
                return ResourceManager.GetString("clearDirCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à clone channel.
        /// </summary>
        internal static string cloneCommand {
            get {
                return ResourceManager.GetString("cloneCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à compress video.
        /// </summary>
        internal static string compressCommand {
            get {
                return ResourceManager.GetString("compressCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à convert messages to a txt file.
        /// </summary>
        internal static string convert2txtCommand {
            get {
                return ResourceManager.GetString("convert2txtCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à convert messages to  zip file.
        /// </summary>
        internal static string convert2zipCommand {
            get {
                return ResourceManager.GetString("convert2zipCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à create rappel.
        /// </summary>
        internal static string createRappelCmd {
            get {
                return ResourceManager.GetString("createRappelCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a ticket.
        /// </summary>
        internal static string createticketCommand {
            get {
                return ResourceManager.GetString("createticketCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à deaf user.
        /// </summary>
        internal static string deafCommand {
            get {
                return ResourceManager.GetString("deafCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à decompress zip file to files.
        /// </summary>
        internal static string decompress2zipCommand {
            get {
                return ResourceManager.GetString("decompress2zipCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à delete song queue.
        /// </summary>
        internal static string deleteAudioCommand {
            get {
                return ResourceManager.GetString("deleteAudioCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à delete channel.
        /// </summary>
        internal static string deleteCommand {
            get {
                return ResourceManager.GetString("deleteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à delete links from channel.
        /// </summary>
        internal static string deletelinksCommand {
            get {
                return ResourceManager.GetString("deletelinksCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à export links from channel.
        /// </summary>
        internal static string exportlinksCommand {
            get {
                return ResourceManager.GetString("exportlinksCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à extract audio from a video file.
        /// </summary>
        internal static string extractCommand {
            get {
                return ResourceManager.GetString("extractCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à extract messages to a txt file.
        /// </summary>
        internal static string extractMessageCommand {
            get {
                return ResourceManager.GetString("extractMessageCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à get film info.
        /// </summary>
        internal static string filmCommand {
            get {
                return ResourceManager.GetString("filmCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à get links from channel.
        /// </summary>
        internal static string getlinksCommand {
            get {
                return ResourceManager.GetString("getlinksCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à et reddit posts by description.
        /// </summary>
        internal static string getpostsbydescriptionRedditCmd {
            get {
                return ResourceManager.GetString("getpostsbydescriptionRedditCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à add grayscale effect.
        /// </summary>
        internal static string grayscaleCommand {
            get {
                return ResourceManager.GetString("grayscaleCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à watch image directory server.
        /// </summary>
        internal static string imageWatchCommand {
            get {
                return ResourceManager.GetString("imageWatchCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à invite to your server.
        /// </summary>
        internal static string inviteCommand {
            get {
                return ResourceManager.GetString("inviteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à bot audio channel join.
        /// </summary>
        internal static string joinAudioCommand {
            get {
                return ResourceManager.GetString("joinAudioCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à leave channel.
        /// </summary>
        internal static string leaveAudioCommand {
            get {
                return ResourceManager.GetString("leaveAudioCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à list song queue.
        /// </summary>
        internal static string listAudioCommand {
            get {
                return ResourceManager.GetString("listAudioCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à list rappel.
        /// </summary>
        internal static string listRappelCmd {
            get {
                return ResourceManager.GetString("listRappelCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List all of tickets.
        /// </summary>
        internal static string listticketCommand {
            get {
                return ResourceManager.GetString("listticketCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à get video metadata.
        /// </summary>
        internal static string metadataCommand {
            get {
                return ResourceManager.GetString("metadataCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mute user.
        /// </summary>
        internal static string muteCommand {
            get {
                return ResourceManager.GetString("muteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à add negative effect.
        /// </summary>
        internal static string negativeCommand {
            get {
                return ResourceManager.GetString("negativeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pause song.
        /// </summary>
        internal static string pauseAudioCommand {
            get {
                return ResourceManager.GetString("pauseAudioCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pile ou face.
        /// </summary>
        internal static string pileoufaceCommand {
            get {
                return ResourceManager.GetString("pileoufaceCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ping sender.
        /// </summary>
        internal static string pingsenderCommand {
            get {
                return ResourceManager.GetString("pingsenderCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ping sender for web.
        /// </summary>
        internal static string pingwebCommand {
            get {
                return ResourceManager.GetString("pingwebCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à play search song.
        /// </summary>
        internal static string playAudioCommand {
            get {
                return ResourceManager.GetString("playAudioCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à create poll.
        /// </summary>
        internal static string pollCommand {
            get {
                return ResourceManager.GetString("pollCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Read rappel.
        /// </summary>
        internal static string readRappelCmd {
            get {
                return ResourceManager.GetString("readRappelCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Read a ticket.
        /// </summary>
        internal static string readticketCommand {
            get {
                return ResourceManager.GetString("readticketCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à remove role to  user.
        /// </summary>
        internal static string removeRoleCommand {
            get {
                return ResourceManager.GetString("removeRoleCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à add sepia effect.
        /// </summary>
        internal static string sepiaCommand {
            get {
                return ResourceManager.GetString("sepiaCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set a ticket checked.
        /// </summary>
        internal static string setticketCommand {
            get {
                return ResourceManager.GetString("setticketCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à set volume.
        /// </summary>
        internal static string setVolumeAudioCommand {
            get {
                return ResourceManager.GetString("setVolumeAudioCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à skip song.
        /// </summary>
        internal static string skipAudioCommand {
            get {
                return ResourceManager.GetString("skipAudioCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à get star info.
        /// </summary>
        internal static string starCommand {
            get {
                return ResourceManager.GetString("starCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à stop song.
        /// </summary>
        internal static string stopAudioCommand {
            get {
                return ResourceManager.GetString("stopAudioCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à get user post.
        /// </summary>
        internal static string getuserpostRedditCmd {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à return random number.
        /// </summary>
        internal static string ramdomCmd {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à get twitch game info.
        /// </summary>
        internal static string gameinfoCmd {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à get steam apps news.
        /// </summary>
        internal static string getsteamnewsCmd {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à get steam apps info by date desc.
        /// </summary>
        internal static string getSteamdatedescCmd {
            get {
                return ResourceManager.GetString("String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à get steam apps info by date asc.
        /// </summary>
        internal static string getSteamdateascCmd {
            get {
                return ResourceManager.GetString("String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à get steam app info by name.
        /// </summary>
        internal static string getSteamappnameCmd {
            get {
                return ResourceManager.GetString("String14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à get steam apps info.
        /// </summary>
        internal static string getSteamappsCmd {
            get {
                return ResourceManager.GetString("String15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à get steam app info.
        /// </summary>
        internal static string getSteamappCmd {
            get {
                return ResourceManager.GetString("String16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à get steam user friendlist.
        /// </summary>
        internal static string getfriendlistCmd {
            get {
                return ResourceManager.GetString("String17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à get steam user info.
        /// </summary>
        internal static string getSteamUserCmd {
            get {
                return ResourceManager.GetString("String18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à get tf golden wrench.
        /// </summary>
        internal static string tfGWCmd {
            get {
                return ResourceManager.GetString("String19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à get discord user avatar.
        /// </summary>
        internal static string avatarcmd {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à get asset.
        /// </summary>
        internal static string assetCmd {
            get {
                return ResourceManager.GetString("String20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à get csgo server status.
        /// </summary>
        internal static string csgoCmd {
            get {
                return ResourceManager.GetString("String21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à get user info.
        /// </summary>
        internal static string getuserinfoRedditCmd {
            get {
                return ResourceManager.GetString("String22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à get count replies.
        /// </summary>
        internal static string getcountreppliesRedditCmd {
            get {
                return ResourceManager.GetString("String23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à get comment on reddit posts by subname &amp; title.
        /// </summary>
        internal static string getCommentSubRedditCmd {
            get {
                return ResourceManager.GetString("String24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à get hot reddit posts by subname.
        /// </summary>
        internal static string getHotpostSubRedditCmd {
            get {
                return ResourceManager.GetString("String25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à get top daily reddit posts by subname.
        /// </summary>
        internal static string getTopDailypostSubRedditCmd {
            get {
                return ResourceManager.GetString("String26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à get best reddit posts by subname.
        /// </summary>
        internal static string getBestpostSubRedditCmd {
            get {
                return ResourceManager.GetString("String27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à get lastest reddit posts by subname.
        /// </summary>
        internal static string getlatestpostSubRedditCmd {
            get {
                return ResourceManager.GetString("String28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à cnvert a site to html.
        /// </summary>
        internal static string convertsite2htmlcmd {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à get twitch stream info.
        /// </summary>
        internal static string gettwitchsteamcmd {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à get twitch user clip.
        /// </summary>
        internal static string getuserclipcmd {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à get latest twitch user clip.
        /// </summary>
        internal static string getlatestuserclipcmd {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à get twitch user emoji.
        /// </summary>
        internal static string twtchEmjiCmd {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à get twitch user info.
        /// </summary>
        internal static string twtchserInfoCmd {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à get twitch user following.
        /// </summary>
        internal static string twtchCmd {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à timeout user.
        /// </summary>
        internal static string timeoutCommand {
            get {
                return ResourceManager.GetString("timeoutCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à add transpiracy effect.
        /// </summary>
        internal static string transpiracyCommand {
            get {
                return ResourceManager.GetString("transpiracyCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à unban user.
        /// </summary>
        internal static string unbanCommand {
            get {
                return ResourceManager.GetString("unbanCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à undeaf user.
        /// </summary>
        internal static string undeafCommand {
            get {
                return ResourceManager.GetString("undeafCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à unmute user.
        /// </summary>
        internal static string unmuteCommand {
            get {
                return ResourceManager.GetString("unmuteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à upload video to bot discord server.
        /// </summary>
        internal static string uploadCommand {
            get {
                return ResourceManager.GetString("uploadCommand", resourceCulture);
            }
        }
    }
}
