// <auto-generated />
using System;
using ApiApplication;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiApplication.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220331150454_migration")]
    partial class migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.2.22153.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BusClassLibrary.Arret", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("stop_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ville")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("xlocation")
                        .HasColumnType("real");

                    b.Property<float>("ylocation")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Arret");
                });

            modelBuilder.Entity("BusClassLibrary.Ligne", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("route_desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("route_short_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("route_text_color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("route_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("_lignes");
                });

            modelBuilder.Entity("BusClassLibrary.Shape", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("lat")
                        .HasColumnType("real");

                    b.Property<float>("longit")
                        .HasColumnType("real");

                    b.Property<int>("sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("_shapes");
                });

            modelBuilder.Entity("BusClassLibrary.StopTimes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("arrival_time")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("departure_time")
                        .HasColumnType("datetime2");

                    b.Property<int>("stop_id")
                        .HasColumnType("int");

                    b.Property<float>("stop_sequence")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("_stopTimes");
                });

            modelBuilder.Entity("BusClassLibrary.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("direction_id")
                        .HasColumnType("int");

                    b.Property<Guid>("service_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("shape_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("trip_headsign")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("_trips");
                });
#pragma warning restore 612, 618
        }
    }
}
